[workspace]
members = ["frontend", "backend", "shared"]

[workspace.package]
#name = "rs-app-mail"
version = "0.1.0"
edition = "2021"

[profile.release]
#codegen-units = 1
#lto = true
#opt-level = 'z'

[workspace.dependencies]